create database "Eastate" with owner=postgres encoding='UTF-8' lc_collate='en_US.utf8' lc_ctype='en_US.utf8' template template1;

CREATE TABLE IF NOT EXISTS public."AllField"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    city text,
	district text,
    flat_type text,
    payment_type text,
    cost_limit text,
    fioandphone text,
    good_time text,
    CONSTRAINT "AllField_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Saratov"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    offer_type text,
    fioandphone text,
    good_time text,
    CONSTRAINT "Saratov_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Consult"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    fioandphone text,
    question text,
    good_time text,
    CONSTRAINT "Consult_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Policy"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    policy_type text,
    offer text,
    fioandphone text,
    position text,
    employer text,
    client_weight text,
    height text,
    diseases text,
    bank text,
    count text,
    building_year text,
    gas text,
    good_time text,
    CONSTRAINT "Policy_pkey" PRIMARY KEY (id)
);